//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE
    {
        public long Payment_Detail_Id { get; set; }
        public long Bank_Id { get; set; }
        public string Cheque_Number { get; set; }
        public string Account_Number { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual PAYMENT_DETAIL PAYMENT_DETAIL { get; set; }
    }
}
