//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_STOCK_PRICE
    {
        public long Stock_Price_Id { get; set; }
    
        public virtual STOCK_PRICE STOCK_PRICE { get; set; }
    }
}
