//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELETED_SOLD_STOCK
    {
        public long Sold_Stock_Id { get; set; }
        public long Shelf_Id { get; set; }
        public long Sold_Stock_Batch_Id { get; set; }
        public long Stock_Price_Id { get; set; }
        public bool Returned { get; set; }
        public long Quantity { get; set; }
    
        public virtual STOCK_PRICE STOCK_PRICE { get; set; }
        public virtual DELETED_SOLD_STOCK_BATCH DELETED_SOLD_STOCK_BATCH { get; set; }
    }
}
