//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELETED_SHELF_STOCK
    {
        public long Shelf_Id { get; set; }
        public long Stock_Package_Id { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public long Quantity { get; set; }
        public long Deleted_By { get; set; }
        public System.DateTime Date_Deleted { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP { get; set; }
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
    }
}
