//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESNECIL
    {
        public long Esnecil_Id { get; set; }
        public string Validation_Key { get; set; }
        public string Machine_Code { get; set; }
        public string Esnecil_Code { get; set; }
        public string Serial_Code { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public bool Is_Evaluation { get; set; }
    
        public virtual CURRENT_ESNECIL CURRENT_ESNECIL { get; set; }
    }
}
