//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPENSES()
        {
            this.EXPENSES_DETAIL = new HashSet<EXPENSES_DETAIL>();
        }
    
        public long Expenses_Id { get; set; }
        public decimal Opening_Balance { get; set; }
        public Nullable<decimal> Additional_Cash { get; set; }
        public decimal Cash_At_Hand { get; set; }
        public decimal Closing_Balance { get; set; }
        public System.DateTime Expenses_Date { get; set; }
        public long Created_By_Person_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPENSES_DETAIL> EXPENSES_DETAIL { get; set; }
    }
}
