//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE_RELATIONSHIP
    {
        public long Package_Relationship_Id { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public long Stock_Package_Id { get; set; }
        public Nullable<long> Sub_Stock_Package_Id { get; set; }
        public decimal Quantity_In_Package { get; set; }
        public long Rank { get; set; }
    
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
        public virtual STOCK_PACKAGE STOCK_PACKAGE1 { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP { get; set; }
    }
}
