//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYMENT()
        {
            this.DELETED_SOLD_STOCK_BATCH = new HashSet<DELETED_SOLD_STOCK_BATCH>();
            this.PAYMENT_DETAIL = new HashSet<PAYMENT_DETAIL>();
            this.RETURNED_STOCK_DETAIL = new HashSet<RETURNED_STOCK_DETAIL>();
            this.SOLD_STOCK_BATCH = new HashSet<SOLD_STOCK_BATCH>();
            this.SOLD_STOCK_RETURN_REFUND = new HashSet<SOLD_STOCK_RETURN_REFUND>();
            this.STOCK_PURCHASE_BATCH = new HashSet<STOCK_PURCHASE_BATCH>();
        }
    
        public long Payment_Id { get; set; }
        public long Transaction_Type_Id { get; set; }
        public decimal Amount_Payable { get; set; }
        public Nullable<long> Serial_Number { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date_Paid { get; set; }
    
        public virtual CASH CASH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SOLD_STOCK_BATCH> DELETED_SOLD_STOCK_BATCH { get; set; }
        public virtual PART PART { get; set; }
        public virtual TRANSACTION_TYPE TRANSACTION_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT_DETAIL> PAYMENT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_DETAIL> RETURNED_STOCK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK_BATCH> SOLD_STOCK_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK_RETURN_REFUND> SOLD_STOCK_RETURN_REFUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASE_BATCH> STOCK_PURCHASE_BATCH { get; set; }
    }
}
