//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_DETAIL
    {
        public long Payment_Detail_Id { get; set; }
        public long Payment_Id { get; set; }
        public long Payment_Type_Id { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public decimal Amount_Paid { get; set; }
    
        public virtual CHEQUE CHEQUE { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
    }
}
