//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_COMPANY
    {
        public long Person_Company_Id { get; set; }
        public long Person_Id { get; set; }
        public long Company_Id { get; set; }
        public string Remarks { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
