//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.DELETED_SHELF_STOCK = new HashSet<DELETED_SHELF_STOCK>();
            this.DELETED_SOLD_STOCK_BATCH = new HashSet<DELETED_SOLD_STOCK_BATCH>();
            this.DELETED_SOLD_STOCK_BATCH1 = new HashSet<DELETED_SOLD_STOCK_BATCH>();
            this.DELETED_SOLD_STOCK_BATCH2 = new HashSet<DELETED_SOLD_STOCK_BATCH>();
            this.EXPENSES = new HashSet<EXPENSES>();
            this.PERSON_COMPANY = new HashSet<PERSON_COMPANY>();
            this.RETURNED_STOCK = new HashSet<RETURNED_STOCK>();
            this.RETURNED_STOCK_REPLACEMENT = new HashSet<RETURNED_STOCK_REPLACEMENT>();
            this.SHELF = new HashSet<SHELF>();
            this.SOLD_STOCK_BATCH = new HashSet<SOLD_STOCK_BATCH>();
            this.SOLD_STOCK_BATCH1 = new HashSet<SOLD_STOCK_BATCH>();
            this.STOCK_PACKAGE_RELATIONSHIP = new HashSet<STOCK_PACKAGE_RELATIONSHIP>();
            this.STOCK_PURCHASE_BATCH = new HashSet<STOCK_PURCHASE_BATCH>();
            this.STOCK_PURCHASE_BATCH1 = new HashSet<STOCK_PURCHASE_BATCH>();
            this.STOCK_PURCHASED_RETURN = new HashSet<STOCK_PURCHASED_RETURN>();
            this.STOCK_REVIEW = new HashSet<STOCK_REVIEW>();
        }
    
        public long Person_Id { get; set; }
        public long Person_Type_Id { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Mobile_Phone { get; set; }
        public string Email { get; set; }
        public string Contact_Address { get; set; }
        public long Role_Id { get; set; }
        public long Location_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SHELF_STOCK> DELETED_SHELF_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SOLD_STOCK_BATCH> DELETED_SOLD_STOCK_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SOLD_STOCK_BATCH> DELETED_SOLD_STOCK_BATCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SOLD_STOCK_BATCH> DELETED_SOLD_STOCK_BATCH2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPENSES> EXPENSES { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_COMPANY> PERSON_COMPANY { get; set; }
        public virtual PERSON_LOGIN PERSON_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK> RETURNED_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_REPLACEMENT> RETURNED_STOCK_REPLACEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHELF> SHELF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK_BATCH> SOLD_STOCK_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK_BATCH> SOLD_STOCK_BATCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PACKAGE_RELATIONSHIP> STOCK_PACKAGE_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASE_BATCH> STOCK_PURCHASE_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASE_BATCH> STOCK_PURCHASE_BATCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_RETURN> STOCK_PURCHASED_RETURN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_REVIEW> STOCK_REVIEW { get; set; }
    }
}
