//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPLACED_STOCK_ACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPLACED_STOCK_ACTION()
        {
            this.RETURNED_STOCK_REPLACEMENT = new HashSet<RETURNED_STOCK_REPLACEMENT>();
            this.STOCK_PURCHASED_RETURN = new HashSet<STOCK_PURCHASED_RETURN>();
        }
    
        public long Replaced_Stock_Action_Id { get; set; }
        public string Replaced_Stock_Action_Name { get; set; }
        public string Replaced_Stock_Action_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_REPLACEMENT> RETURNED_STOCK_REPLACEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_RETURN> STOCK_PURCHASED_RETURN { get; set; }
    }
}
