//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNED_STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETURNED_STOCK()
        {
            this.RETURNED_STOCK_DETAIL = new HashSet<RETURNED_STOCK_DETAIL>();
        }
    
        public long Returned_Stock_Id { get; set; }
        public System.DateTime Return_Date { get; set; }
        public string Return_Reason { get; set; }
        public string Remarks { get; set; }
        public long Entered_By { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_DETAIL> RETURNED_STOCK_DETAIL { get; set; }
    }
}
