//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNED_STOCK_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETURNED_STOCK_DETAIL()
        {
            this.RETURNED_STOCK_REPLACEMENT = new HashSet<RETURNED_STOCK_REPLACEMENT>();
        }
    
        public long Returned_Stock_Detail_Id { get; set; }
        public long Sold_Stock_Id { get; set; }
        public long Returned_Stock_Id { get; set; }
        public long Returned_Quantity { get; set; }
        public long Stock_State_Id { get; set; }
        public long Stock_Return_Action_Id { get; set; }
        public bool Refunded { get; set; }
        public Nullable<long> Payment_Id { get; set; }
        public bool Returned_To_Shelf { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual RETURNED_STOCK RETURNED_STOCK { get; set; }
        public virtual STOCK_RETURN_ACTION STOCK_RETURN_ACTION { get; set; }
        public virtual STOCK_STATE STOCK_STATE { get; set; }
        public virtual SOLD_STOCK SOLD_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_REPLACEMENT> RETURNED_STOCK_REPLACEMENT { get; set; }
    }
}
