//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public long Setting_Id { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
        public long Application_Mode_Id { get; set; }
        public bool Is_Customer_Loyalty_Enabled { get; set; }
        public bool Show_Package_Relationship_In_Stock_Summary_Review_Report { get; set; }
        public bool Is_Activated { get; set; }
    
        public virtual APPLICATION_MODE APPLICATION_MODE { get; set; }
    }
}
