//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHELF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHELF()
        {
            this.SOLD_STOCK = new HashSet<SOLD_STOCK>();
        }
    
        public long Shelf_Id { get; set; }
        public long Stock_Package_Id { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public long Entered_By { get; set; }
        public long Location_Id { get; set; }
        public long Quantity { get; set; }
        public decimal Total_Unit_Quantity { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public bool Sold { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP { get; set; }
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK> SOLD_STOCK { get; set; }
    }
}
