//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHELF_STOCK_REPLACEMENT
    {
        public long Shelf_Id { get; set; }
        public long Stock_Package_Id { get; set; }
        public long Quantity_Replaced { get; set; }
        public System.DateTime Date_Replaced { get; set; }
    
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
    }
}
