//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLD_STOCK_RETURN_REFUND
    {
        public long Stock_On_Shelf_Id { get; set; }
        public long Payment_Id { get; set; }
        public string Remarks { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual SOLD_STOCK_RETURN SOLD_STOCK_RETURN { get; set; }
    }
}
