//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLD_STOCK_RETURN
    {
        public long Stock_On_Shelf_Id { get; set; }
        public long Stock_State_Id { get; set; }
        public long Stock_Package_Id { get; set; }
        public long Quantity_Returned { get; set; }
        public System.DateTime Date_Returned { get; set; }
        public string Return_Reason { get; set; }
        public bool Replaced { get; set; }
        public bool Refunded { get; set; }
        public bool Back_To_Stock_Purchased { get; set; }
    
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
        public virtual STOCK_STATE STOCK_STATE { get; set; }
        public virtual SOLD_STOCK_RETURN_REFUND SOLD_STOCK_RETURN_REFUND { get; set; }
    }
}
