//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLD_STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLD_STOCK()
        {
            this.RETURNED_STOCK_DETAIL = new HashSet<RETURNED_STOCK_DETAIL>();
            this.RETURNED_STOCK_REPLACEMENT = new HashSet<RETURNED_STOCK_REPLACEMENT>();
        }
    
        public long Sold_Stock_Id { get; set; }
        public long Shelf_Id { get; set; }
        public long Sold_Stock_Batch_Id { get; set; }
        public long Stock_Price_Id { get; set; }
        public long Quantity { get; set; }
        public decimal Discount { get; set; }
        public bool Returned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_DETAIL> RETURNED_STOCK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_REPLACEMENT> RETURNED_STOCK_REPLACEMENT { get; set; }
        public virtual SHELF SHELF { get; set; }
        public virtual STOCK_PRICE STOCK_PRICE { get; set; }
        public virtual SOLD_STOCK_BATCH SOLD_STOCK_BATCH { get; set; }
    }
}
