//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PACKAGE_RELATIONSHIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_PACKAGE_RELATIONSHIP()
        {
            this.DELETED_SHELF_STOCK = new HashSet<DELETED_SHELF_STOCK>();
            this.PACKAGE_RELATIONSHIP = new HashSet<PACKAGE_RELATIONSHIP>();
            this.SHELF = new HashSet<SHELF>();
            this.STOCK_PURCHASED = new HashSet<STOCK_PURCHASED>();
            this.STOCK_PURCHASED_POOL = new HashSet<STOCK_PURCHASED_POOL>();
            this.STOCK_PURCHASED_POOL1 = new HashSet<STOCK_PURCHASED_POOL>();
            this.STOCK_PURCHASED_RETURN = new HashSet<STOCK_PURCHASED_RETURN>();
        }
    
        public long Stock_Package_Relationship_Id { get; set; }
        public long Stock_Id { get; set; }
        public System.DateTime Date_Set { get; set; }
        public long Set_By_Person_Id { get; set; }
    
        public virtual CURRENT_STOCK_PACKAGE_RELATIONSHIP CURRENT_STOCK_PACKAGE_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SHELF_STOCK> DELETED_SHELF_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGE_RELATIONSHIP> PACKAGE_RELATIONSHIP { get; set; }
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHELF> SHELF { get; set; }
        public virtual STOCK STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED> STOCK_PURCHASED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_POOL> STOCK_PURCHASED_POOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_POOL> STOCK_PURCHASED_POOL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_RETURN> STOCK_PURCHASED_RETURN { get; set; }
    }
}
