//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PURCHASE_BATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_PURCHASE_BATCH()
        {
            this.STOCK_PURCHASED = new HashSet<STOCK_PURCHASED>();
            this.STOCK_PURCHASED_POOL = new HashSet<STOCK_PURCHASED_POOL>();
            this.STOCK_PURCHASED_RETURN = new HashSet<STOCK_PURCHASED_RETURN>();
        }
    
        public long Stock_Purchase_Batch_Id { get; set; }
        public long Stock_Purchase_Batch_Type_Id { get; set; }
        public long Supplier_Id { get; set; }
        public long Buyer_Id { get; set; }
        public long Payment_Id { get; set; }
        public System.DateTime Date_Puchased { get; set; }
        public Nullable<decimal> Supplier_Expenses { get; set; }
        public string Invoice_Number { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON PERSON1 { get; set; }
        public virtual STOCK_PURCHASE_BATCH_TYPE STOCK_PURCHASE_BATCH_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED> STOCK_PURCHASED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_POOL> STOCK_PURCHASED_POOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_RETURN> STOCK_PURCHASED_RETURN { get; set; }
    }
}
