//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PURCHASED
    {
        public long Stock_Purchased_Id { get; set; }
        public long Stock_Purchase_Batch_Id { get; set; }
        public long Stock_Id { get; set; }
        public long Stock_Package_Id { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public long Quantity { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
    
        public virtual STOCK STOCK { get; set; }
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP { get; set; }
        public virtual STOCK_PURCHASE_BATCH STOCK_PURCHASE_BATCH { get; set; }
        public virtual STOCK_PURCHASED_POOL_DETAIL STOCK_PURCHASED_POOL_DETAIL { get; set; }
    }
}
