//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PURCHASED_POOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_PURCHASED_POOL()
        {
            this.STOCK_PURCHASED_POOL_DETAIL = new HashSet<STOCK_PURCHASED_POOL_DETAIL>();
        }
    
        public long Stock_Purchased_Pool_Id { get; set; }
        public long Stock_Purchase_Batch_Id { get; set; }
        public long Stock_Id { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public long Unit_Item_Package_Id { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual STOCK STOCK { get; set; }
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP1 { get; set; }
        public virtual STOCK_PURCHASE_BATCH STOCK_PURCHASE_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_POOL_DETAIL> STOCK_PURCHASED_POOL_DETAIL { get; set; }
    }
}
