//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PURCHASED_RETURN
    {
        public long Stock_Purchased_Return_Id { get; set; }
        public long Stock_Purchase_Batch_Id { get; set; }
        public long Quantity { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Cost { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public Nullable<long> Stock_Package_Id { get; set; }
        public long Stock_State_Id { get; set; }
        public Nullable<long> Replaced_Stock_Action_Id { get; set; }
        public string Return_Reason { get; set; }
        public System.DateTime Date_Returned { get; set; }
        public Nullable<long> Returned_By_Person_Id { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual REPLACED_STOCK_ACTION REPLACED_STOCK_ACTION { get; set; }
        public virtual STOCK_PACKAGE STOCK_PACKAGE { get; set; }
        public virtual STOCK_PACKAGE_RELATIONSHIP STOCK_PACKAGE_RELATIONSHIP { get; set; }
        public virtual STOCK_PURCHASE_BATCH STOCK_PURCHASE_BATCH { get; set; }
        public virtual STOCK_STATE STOCK_STATE { get; set; }
    }
}
