//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_REPLACEMENT
    {
        public long Stock_Purchase_Batch_Id { get; set; }
        public long Stock_Id { get; set; }
        public long Stock_Quantity_Id { get; set; }
        public decimal Replaced_Quantity { get; set; }
        public System.DateTime Date_Replaced { get; set; }
    }
}
