//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_STATE()
        {
            this.RETURNED_STOCK_DETAIL = new HashSet<RETURNED_STOCK_DETAIL>();
            this.SOLD_STOCK_RETURN = new HashSet<SOLD_STOCK_RETURN>();
            this.STOCK_PURCHASED_RETURN = new HashSet<STOCK_PURCHASED_RETURN>();
        }
    
        public long Stock_State_Id { get; set; }
        public string Stock_State_Name { get; set; }
        public string Stock_State_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_STOCK_DETAIL> RETURNED_STOCK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK_RETURN> SOLD_STOCK_RETURN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_RETURN> STOCK_PURCHASED_RETURN { get; set; }
    }
}
