//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_REVIEW_DETAIL
    {
        public long Stock_Review_Detail_Id { get; set; }
        public long Stock_Review_Id { get; set; }
        public long Stock_Id { get; set; }
        public string Stock_Name { get; set; }
        public long Stock_Package_Relationship_Id { get; set; }
        public string Initial_Stock_Balance { get; set; }
        public Nullable<decimal> Initial_Stock_Balance_Value { get; set; }
        public string Stock_Balance { get; set; }
        public Nullable<decimal> Stock_Balance_Value { get; set; }
        public decimal Stock_Balance_Unit_Item { get; set; }
        public string Quantity_Purchased { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Quantity_Sold { get; set; }
        public Nullable<decimal> Cost_Price { get; set; }
        public Nullable<decimal> Selling_Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Profit2 { get; set; }
        public string Package_Relationship { get; set; }
        public Nullable<long> Transaction_Month { get; set; }
        public Nullable<long> Transaction_Year { get; set; }
        public Nullable<decimal> Monthly_Total_Expenses { get; set; }
        public Nullable<decimal> Monthly_Transaction_Discount { get; set; }
    
        public virtual STOCK_REVIEW STOCK_REVIEW { get; set; }
    }
}
