//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PURCHASED_POOL_DETAIL
    {
        public long Stock_Purchased_Id { get; set; }
        public long Stock_Purchased_Pool_Id { get; set; }
        public string Remarks { get; set; }
    
        public virtual STOCK_PURCHASED STOCK_PURCHASED { get; set; }
        public virtual STOCK_PURCHASED_POOL STOCK_PURCHASED_POOL { get; set; }
    }
}
