//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_REVIEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_REVIEW()
        {
            this.STOCK_REVIEW_DETAIL = new HashSet<STOCK_REVIEW_DETAIL>();
        }
    
        public long Stock_Review_Summary_Id { get; set; }
        public long Reviewed_By_Person_Id { get; set; }
        public long Review_Year { get; set; }
        public System.DateTime Review_Date { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_REVIEW_DETAIL> STOCK_REVIEW_DETAIL { get; set; }
    }
}
