//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokno.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PACKAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_PACKAGE()
        {
            this.DELETED_SHELF_STOCK = new HashSet<DELETED_SHELF_STOCK>();
            this.PACKAGE_RELATIONSHIP = new HashSet<PACKAGE_RELATIONSHIP>();
            this.PACKAGE_RELATIONSHIP1 = new HashSet<PACKAGE_RELATIONSHIP>();
            this.SHELF = new HashSet<SHELF>();
            this.SHELF_STOCK_REPLACEMENT = new HashSet<SHELF_STOCK_REPLACEMENT>();
            this.SOLD_STOCK_RETURN = new HashSet<SOLD_STOCK_RETURN>();
            this.STOCK_PRICE = new HashSet<STOCK_PRICE>();
            this.STOCK_PURCHASED = new HashSet<STOCK_PURCHASED>();
            this.STOCK_PURCHASED_POOL = new HashSet<STOCK_PURCHASED_POOL>();
            this.STOCK_PURCHASED_RETURN = new HashSet<STOCK_PURCHASED_RETURN>();
        }
    
        public long Stock_Package_Id { get; set; }
        public long Package_Id { get; set; }
        public long Stock_Id { get; set; }
        public string Stock_Package_Description { get; set; }
        public long Re_Order_Level { get; set; }
        public long Expiry_Date_No_Of_Days_Alert { get; set; }
    
        public virtual CURRENT_STOCK_PACKAGE CURRENT_STOCK_PACKAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELETED_SHELF_STOCK> DELETED_SHELF_STOCK { get; set; }
        public virtual PACKAGE PACKAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGE_RELATIONSHIP> PACKAGE_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGE_RELATIONSHIP> PACKAGE_RELATIONSHIP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHELF> SHELF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHELF_STOCK_REPLACEMENT> SHELF_STOCK_REPLACEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_STOCK_RETURN> SOLD_STOCK_RETURN { get; set; }
        public virtual STOCK STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PRICE> STOCK_PRICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED> STOCK_PURCHASED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_POOL> STOCK_PURCHASED_POOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PURCHASED_RETURN> STOCK_PURCHASED_RETURN { get; set; }
    }
}
